### ISSUE TITLE
Something is not implemented ..

### ISSUE THREAD

**Issue by rcatwood** [DiamondLightSource/Savu#206]
Traceback (most recent call last):
  File "/home/kny48981/progs/savu_fork/Savu/savu/tomo_recon.py", line 93, in <module>
    main()
  File "/home/kny48981/progs/savu_fork/Savu/savu/tomo_recon.py", line 89, in main
    plugin_runner.run_plugin_list(options)
  File "/home/kny48981/progs/savu_fork/Savu/savu/core/plugin_runner.py", line 66, in run_plugin_list
    self.transport_run_plugin_list()
  File "/home/kny48981/progs/savu_fork/Savu/savu/core/transports/hdf5_transport.py", line 149, in transport_run_plugin_list
    self.real_plugin_run(plugin_list, out_data_objs, start, stop)
  File "/home/kny48981/progs/savu_fork/Savu/savu/core/transports/hdf5_transport.py", line 173, in real_plugin_run
    plugin.run_plugin(exp, self)
  File "/home/kny48981/progs/savu_fork/Savu/savu/plugins/driver/cpu_plugin.py", line 37, in run_plugin
    self.run_plugin_instances(transport)
  File "/home/kny48981/progs/savu_fork/Savu/savu/plugins/driver/plugin_driver.py", line 56, in run_plugin_instances
    transport.process(self)
  File "/home/kny48981/progs/savu_fork/Savu/savu/core/transports/hdf5_transport.py", line 205, in process
    result = plugin.process_frames(section, slice_list)
  File "/home/kny48981/progs/savu_fork/Savu/savu/plugins/base_filter.py", line 64, in process_frames
    return self.filter_frames(data)
  File "/home/kny48981/progs/savu_fork/Savu/savu/plugins/base_filter.py", line 72, in filter_frames
    raise NotImplementedError("process needs to be implemented")
NotImplementedError: process needs to be implemented

**Comment by nicwade** [comment]
Hi Robert,

Are you trying to create a new plugin that inherits from BaseFilter?  If
so, then your plugin MUST have a filter_frames method as its main
processing method, otherwise it will throw a not implemented error.  See
any plugin in savu/plugins/filters for examples.

If you were not writing a new plugin then please could you send me some
more information so I can try and recreate the error.  Thanks.

**Comment by rcatwood** [comment]
Hi,
Nothing to do with developing any new plugin. Just trying to apply existing plugins on some data.

The data is ‘relatively’ small . (x=960 y=512 proj=901) and this was only trying the preview of a central slice.
Running on the local machine i12-ws011 (GPU but not MPI)


The package of information is here:

/dls/tmp/savu_bug_data (500 MB)

Including the input file, logs, output files, process list. (worm.savu)

Thanks
Robert

**Comment by nicwade** [comment]
Apologies, the ring_artefact_filter is not working at the moment - this
version is based on the original Manchester code. If you replace it with
raven_filter, which is Nghia's implementation, the problem should be
resolved.

Thanks,

Nicola.

**Comment by rcatwood** [comment]
I see..


n  Suggest rename of both of these , ring_titarenko and ring_raven or similar names  such that the word ‘ring’ and an identifier of the  specific version is in the name of each – (more generally , the purpose of the filter included in the name)

n  Suggest  hiding/removing ones that don’t work from the release

In this case , I was specifically wanting to run Titarenko’s routine in order to as closely as possible duplicate the previous results using specific parameters but also include de-zinger (for which the most up-t-date debugged version is the plugin!)
Old-method (tiff scripts) without dezinger, manchester ring and Paganin:
Many zingers ☹ well, quite a few




[cid:image001.jpg@01D18F35.EB679D90]

**Comment by rcatwood** [comment]
it's closed ... but what is the resolution?
