### ISSUE TITLE
Setting Angles with python statement does not work in ImageLoader plugin

### ISSUE THREAD

**Issue by StephenNneji** [DiamondLightSource/Savu#731]
Setting the angle via a python statement does not works e.g.
```
    add ImageLoader                 
    mod 1.3 np.linspace(0, 359.882996, 459)
```
The problem is most likely because the exec command on line 128 of image_loader.py does not change the local variable angles see explanation [here](https://stackoverflow.com/questions/1463306/how-does-exec-work-with-locals)
```
exec("angles = " + angles)
```

**Comment by dkazanc** [comment]
thanks @StephenNneji I'll look into this. What error are you getting exactly?

**Comment by StephenNneji** [comment]
```
Traceback (most recent call last):
  File "/home/stephen/miniconda3/envs/imaging/bin/savu", line 33, in <module>
    sys.exit(load_entry_point('savu==3.0', 'console_scripts', 'savu')())
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/tomo_recon.py", line 216, in main
    plugin_runner._run_plugin_list()
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/core/plugin_runner.py", line 51, in _run_plugin_list
    self._run_plugin_list_setup(plugin_list)
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/core/plugin_runner.py", line 144, in _run_plugin_list_setup
    pu.plugin_loader(self.exp, plist[i])
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/plugins/utils.py", line 120, in plugin_loader
    check=check)
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/plugins/utils.py", line 88, in get_plugin
    instance.initialise(params, exp, check=check)
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/plugins/plugin.py", line 63, in initialise
    self._main_setup()
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/plugins/loaders/base_loader.py", line 49, in _main_setup
    data_obj = self.setup()
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/plugins/loaders/full_field_loaders/image_loader.py", line 78, in setup
    self.set_rotation_angles(data_obj)
  File "/home/stephen/miniconda3/envs/imaging/lib/python3.7/site-packages/savu-3.0-py3.7.egg/savu/plugins/loaders/full_field_loaders/image_loader.py", line 140, in set_rotation_angles
    "dimension length %s", n_angles, data_angles)
Exception: ('The number of angles %s does not match the data dimension length %s', 31, 459)

```

**Comment by dkazanc** [comment]
thanks, and you're reading 459 images exactly as an input?

**Comment by StephenNneji** [comment]
yes

**Comment by dkazanc** [comment]
@StephenNneji thanks for finding it and for the solution, Need to have a look at other "execs" we've got. The fix should be in the master branch now.
